### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by HackerMan1993** [HackerMan1993/Sports_Revenue_Fans_Etc#1]
Hi @AaronGullickson. I'm finally doing my own stats now instead of helping the undergrads with STATA (thank god). I just have a quick question. How do I load in an Excel file as my data set? I was able to import it in through R Studio (thanks for the suggestions from Thursday, it definitely looks cleaner), but do I need to save it then or do I have the script just read the Excel/ .xlsx file? I'm on step four of the "Get Data" assignment.

**Comment by HackerMan1993** [comment]
Hi again, @AaronGullickson. Same thing with the "Prepare Analytical Dataset," I switched teams' tournament results into a numerical value, replaced my missing values (the only ones I had were revenue for the current year), have smaller sets of my variables, don't need a compound variable, and have only the variables I need. I just need help with the coding into factor variables, a double-check on my "NA" values, and the proper way to save my data set. Sorry this has taken me so long!

**Comment by AaronGullickson** [comment]
@HackerMan1993 

You always want to read it in using the script, so that its reproducible. When you use the "import" menu in RStudio to read it in, it will also give you the code snippet that does the work, so you can just copy and paste that. It should look something like:

```r
library(read_xl)
my_data <- read_excel("path/to/data")
```

You will need to push all of your stuff to GitHub and show me where you need help with coding factor variables for me to be able to help with that.
